version: '3.9'
services:
  api:
    image: ghcr.io/ouassimboutalliss/facialreconstruction_homeproject:v2
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env
    ports:
      - 5000:80